//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalUsuarioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosAcademicos
    {
        public int idDatos { get; set; }
        public int id { get; set; }
        public string titulo { get; set; }
        public string centroEstudios { get; set; }
        public System.DateTime fechaGrado { get; set; }
        public string subirTitulo { get; set; }
    
        public virtual UsuarioDocente UsuarioDocente { get; set; }
    }
}
