//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalUsuarioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discapacidad
    {
        public int id { get; set; }
        public int idDiscapacidad { get; set; }
        public string discapacidad1 { get; set; }
        public string descDiscapacidad { get; set; }
    
        public virtual UsuarioDocente UsuarioDocente { get; set; }
    }
}
