//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalUsuarioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experencias
    {
        public int idExpe { get; set; }
        public int id { get; set; }
        public System.DateTime f_Inicio { get; set; }
        public System.DateTime f_Fin { get; set; }
        public string cargo { get; set; }
        public string empresa { get; set; }
        public string certificado { get; set; }
    
        public virtual UsuarioDocente UsuarioDocente { get; set; }
    }
}
