//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalUsuarioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDocente
    {
        public int id { get; set; }
        public int sexo { get; set; }
        public int estadoCivil { get; set; }
        public string direccion { get; set; }
        public string ubigeo { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string foto { get; set; }
        public System.DateTime fNacimiento { get; set; }
        public System.DateTime fRegistro { get; set; }
        public System.DateTime fModficacion { get; set; }
        public decimal precio_Hora { get; set; }
    
        public virtual EstadoCivil EstadoCivil1 { get; set; }
        public virtual Sexo Sexo1 { get; set; }
        public virtual Ubigeo Ubigeo1 { get; set; }
        public virtual UsuarioDocente UsuarioDocente { get; set; }
    }
}
