insert Cursos(curso) values
('Modelado y diseño de BD'),
('Fundamentos de redes'),
('Internet de las cosas'),
('Matemática aplicada a las tecnologías'),
('Herramientas informáticas básicas'),
('Comunicación efectiva'),
('Fundamentos de programación'),
('Taller de programación'),
('IT Essentials - Ensamblaje'),
('liderazgo y trabajo en equipo'),
('Educación financiera (virtual)'),
('Análisis y diseño de sistemas avanzado'),
('Aplicaciones web'),
('Gestión de proyectos de TI'),
('Emprendimiento tecnológico'),
('Lenguaje de programación - Java web'),
('Administración de base de datos'),
('Experiencias formativas intermedias'),
('Técnicas de programación orientada a objetos'),
('1 Essentials - Conectividad'),
('Ética y ciudadanía'),
('Cableado estructurado'),
('Estructura de datos'),
('Bose de datos'),
('Reparación y mantenimiento de hardware'),
('Experiencias formativas básicas'),
('Gestión de procesos informáticos'),
('Lenguaje de programación avanzado'),
('Taller de programación web'),
('Calidad de software'),
('Administración avanzada de BD'),
('Servicios web'),
('Innovación tecnológica'),
('Análisis y diseño de sistemas'),
('Base de datos avanzado'),
('Lenguaje de programación - Java'),
('Sistemas operativos - Linux'),
('Diseño básico de redes - CCNA 1'),
('Desarrollo de soluciones empresariales'),
('Ambiente y desarrollo'),
('Inteligencia de negocios'),
('Gestión estratégica empresarial'),
('Aplicaciones móviles'),
('Diseño y desarrollo del proyecto productivo innovador (virtual)'),
('Gestión de servicios - ITIL'),
('E-business'),
('Certificación Oracle'),
('Experiencias formativas especializadas');
